In [1]:
import pandas as pd
import numpy as np

In [3]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [4]:
df = pd.read_excel(r"C:\Users\amirb\Desktop\Personal\titus_dashboard\titus_data.xlsx", sheet_name =Data)
df

                YEAR          (全部) Unnamed: 2 Unnamed: 3 Unnamed: 4
0             SEASON          (全部)        NaN        NaN        NaN
1               DATE          (全部)        NaN        NaN        NaN
2        Client code          (全部)        NaN        NaN        NaN
3                NaN           NaN        NaN        NaN        NaN
4   计数项:Shipment NO.  Client level        NaN        NaN        NaN
..               ...           ...        ...        ...        ...
81       Destination          (全部)        NaN        NaN        NaN
82               NaN           NaN        NaN        NaN        NaN
83               NaN  Client level        NaN        NaN        NaN
84               NaN        NORMAL     OFFICE        VIP      TOTAL
85      TOTAL:WEIGHT         443.8    7355.58     3039.3   10838.68

[86 rows x 5 columns]